### ISSUE TITLE
Compact api

### ISSUE THREAD

**Issue by roemhildtg** [steveoh/esrislurp#7]
For example, http://js.arcgis.com/3.13compact/

**Comment by steveoh** [comment]
It does not, but it could. It would only take a bit of work. If you wanted to do the work that would be great!  

[ ] Download the 3.13 api
[ ] Add a `compact: true` flag to `grunt-esri-slurp` that defaults to `false`
[ ] Modify `grunt-esri-slurp` to create a module list from the compact api.
[ ] Modify `esrislurp` to read the compact flag and update the url and location of the module list.

**Comment by phillipgreenii** [comment]
I have started working on this.  Is the official process documented anywhere on how to download the API and then convert it to a esriModules-3.11.js?

**Comment by steveoh** [comment]
@phillipgreenii let's start with https://github.com/steveoh/esrislurp/wiki/How-to-create-a-module-list

**Comment by phillipgreenii** [comment]
Exactly what I needed!  Thanks!

**Comment by steveoh** [comment]
closed by 8c9604fa732baaaeae5a1b5fada6666b79569146
